Better assign_partner function
futurelabmx/secret-santa pull request #1
Opened 2019-12-23 00:32 UTC by scratchmex

La función es mas rápida

2020-01-26 23:04 UTC, RodolfoFerro requested changes
Hola @scratchmex, ¡muchas gracias por tu aporte!

Ya revisé el PR y haciendo pruebas noté dos cosas:
1. La asignación de emails no excluye la auto-asignación.
2. La asignación de emails no es única, pues dos emails pueden tener un tercer (que sea el mismo) mismo asignado.

Adjunto un screenshot ilustrando el caso, espero puedas modificar un poco tu propuesta. :roocket:

<img width="1280" alt="Screen Shot 2020-01-26 at 5 01 20 PM" src="https://user-images.githubusercontent.com/8453749/73143249-7e1a2400-405d-11ea-9c04-67beb63eb3d8.png">

2020-02-26 00:21 UTC, scratchmex reviewed
No vi tu respuesta!. Mi error estuvo medio tonto pero creo que ahora si funciona. Para evitar esto añadí algunos tests.

2020-04-12 04:25 UTC, RodolfoFerro commented
¡Hola!

@scratchmex, ¿en qué parte corres las pruebas?

2020-04-12 16:42 UTC, scratchmex commented
Solo corres `pytest` en el directorio raiz (`pip install pytest` si aún no tienes esa maravilla).

2020-04-12 22:54 UTC, RodolfoFerro approved these changes

2020-04-12 22:54 UTC, merged